### ISSUE TITLE
USB Vendor and Product ID setting doesn't take effect

### ISSUE THREAD

**Issue by ejj28** [jangxx/node-ViGEmClient#2]
When setting the USB VID and PID, the VID and PID don't change in Device Manager, I'm guessing this is an issue with my code?
Code:
```let client = new ViGEmClient();
client.connect();
let controller = client.createX360Controller();
controller.connect();
controller.vendorID = 0x1BAD;
controller.productID = 0x0003;

**Comment by jangxx** [comment]
Apparently you can only change the VID and PID before connecting the controller as Windows will not use the modified ids afterwards. This is impossible to do with the current version of the library though, but I'm already working on a fix.

**Comment by ejj28** [comment]
Ah, ok. Thanks!

**Comment by jangxx** [comment]
I just pushed the commit. The `connect()` method on the controller object now takes an optional options parameter, which allows you to specify the ids:

```javascript
let controller = client.createX360Controller();
let err = controller.connect({
    vendorID: 0x1234,
    productID: 0x5678
});
```

Let me know if the update works for you and I will publish version 1.1.0 to npm.

**Comment by ejj28** [comment]
Seems to be working, I can see the updated IDs in device manager. Thanks again!

**Comment by jangxx** [comment]
Okay, version 1.1.0 has been published to npm.
