### ISSUE TITLE
Left trigger and right trigger for xBox controller?

### ISSUE THREAD

**Issue by davidcallanan** [jangxx/node-ViGEmClient#4]
Hello again, as you suggested I switched to using ViGEm :)

This is working perfectly, except I can't figure out how to enable/disable the left an right triggers on an xbox controller? How can I do this?

I've tried using `LEFT/RIGHT_SHOULDER` and `LEFT/RIGHT_THUMB` to no avail.

**Comment by davidcallanan** [comment]
Nevermind, I figured it out, `leftTrigger` and `rightTrigger` are axes, not buttons.

**Comment by Shvarpa** [comment]
in general for triggers:
controller.axis.leftTrigger.setValue(1); // press in left trigger all the way
controller.axis.rightTrigger.setValue(1); // press in right trigger all the way

and for shoulders: (different button on xbox and ds4)
x360controller.button.LEFT_SHOULDER.setValue(true); // presses the left shoulder button on xbox controller;
x360controller.button.RIGHT_SHOULDER.setValue(true) // presses the right shoulder button on xbox controller;

ds4controller.button.SHOULDER_LEFT.setValue(true) // presses the right shoulder button on ds4 controller;
ds4controller.button.SHOULDER_RIGHT.setValue(true) // presses the right shoulder button on ds4 controller;

on ds4 the trigger is a button as well as an axis, so to press the triggers you should press both the corresponding button and the trigger:

ds4controller.button.TRIGGER_LEFT.setValue(true);
ds4controller.axis.leftTrigger.setValue(1);

ds4controller.button.TRIGGER_RIGHT.setValue(true);
ds4controller.axis.rightTrigger.setValue(1);
