### ISSUE TITLE
Trouble Connecting to Client

### ISSUE THREAD

**Issue by ekrenzin** [jangxx/node-ViGEmClient#8]
Issue: Trouble Connecting to Client
-

**What**
- The client will not connect with `client.connect()`
![image](https://user-images.githubusercontent.com/33398104/116128797-2e6e4200-a67e-11eb-86fd-810e2b112b1e.png)
![image](https://user-images.githubusercontent.com/33398104/116128904-4fcf2e00-a67e-11eb-8fbf-f7a0a1039091.png)

**When**
- This is a new issue, until recently everything was working as expected.

**Comment by jangxx** [comment]
Have you checked the return value of the `connect()` call? It will be `null` on success and an `Error` object if there was a problem. The error will hopefully contain some useful information.

**Comment by ekrenzin** [comment]
@jangxx Thanks for the fast reply! It throws an error, but the error doesn't lead me anywhere - maybe it will make more sense to you?

Here:

```
  const ViGEmClient = require('vigemclient')
  client = new ViGEmClient()
  const connection = client.connect()
  console.log({connection})
```
output of console.log: 
![image](https://user-images.githubusercontent.com/33398104/116134889-47c6bc80-a685-11eb-93ac-fcfc03647fa7.png)


ViGEmClient.js:34:31:
![image](https://user-images.githubusercontent.com/33398104/116135046-73e23d80-a685-11eb-8957-cdc8914df34e.png)

slight note: I added a console log in the ViGEmClient.js:34:31 to confirm the clientHandle was not the problem

**Comment by jangxx** [comment]
That's a bit weird, usually the error should contain an error message. Can you try to `console.log` the `errCode` from the connect method? Maybe it returns an error that is not contained in the `VIGEM_ERRORS` object.

**Comment by ekrenzin** [comment]
Certainly @jangxx!

Test:
-
![image](https://user-images.githubusercontent.com/33398104/116139704-28cb2900-a68b-11eb-9a19-19589e038538.png)
![image](https://user-images.githubusercontent.com/33398104/116139664-1ea92a80-a68b-11eb-8441-d0dbfd25fb5f.png)

Error codes:
-
![image](https://user-images.githubusercontent.com/33398104/116139884-629c2f80-a68b-11eb-96af-ef5bcb8991a7.png)

Result:
-
Somehow the errorcode is a negative value and is `-536870911` instead of `'536870912': 'VIGEM_ERROR_NONE'` (1 instead of 2)

**Comment by jangxx** [comment]
Apparently there is a bug in the native code for the `connect()` function that incorrectly casts the returned error code to a negative number. A fix is already on the way for that bug, maybe that will fix your problem as well. ~~Apparently the error code is correct (i.e. it is VIGEM_ERROR_NONE), just the conversion to a javascript `Number` seems wrong somehow.~~

**Comment by jangxx** [comment]
I have just pushed version 1.2.1 to git. Can you please clone the repo and see if that changes anything about your problem? If it does I would publish it to npm.

**Comment by ekrenzin** [comment]
> I have just pushed version 1.2.1 to git. Can you please clone the repo and see if that changes anything about your problem? If it does I would publish it to npm.

Will do @jangxx, I'll let you know soon, thanks a ton!

**Comment by ekrenzin** [comment]
@jangxx just a heads up - I realized that I wasn't using the latest driver - oops! I'm stilling getting errors though - it's unclear why. I will hopefully have some more answers by the end of day or tomorrow. Will keep you updated. Thanks!

**Comment by jangxx** [comment]
I looked at your error code again (-536870911) and if you convert that to an unsigned integer, you get 3758096385, i.e. VIGEM_ERROR_BUT_NOT_FOUND. Maybe you could try to just restart your PC and then retry the installation of the bus driver.

**Comment by ekrenzin** [comment]
@jangxx after updating to the latest git commit I was able to indentify that error (so the most recent commit you pushed up is working great), but a new error came up which I wanted to investigate - I don't have time to explain/document at the moment. My computer actually blue screened a few times. I'll hopefully work on figuring it out tonight/tomorrow. Thanks!

**Comment by ekrenzin** [comment]
@jangxx here is what I have surmised:

The old driver (see below) is no longer supported by this package - at least it seems that way. I was using the old driver and updated to the new driver and restarted my computer. For whatever reason that was not effective. When I tested after restarting I got a spam of pings - the one you hear when a device connects to a usb port. After a bit my computer froze up and blue screened. This same thing happened on my coworkers device. It was actually the original bug I was hunting. After deleteing the old driver by running the executable and choosing the option "remove" then installing the latest driver and finally restarting, the problem seems to have resolved.

It seems I need to do a little bit of refactoring to finish making sure everything works again - but I think the onous is on me now. Thanks a ton for the support - it was really great working with you!

old driver:
![image](https://user-images.githubusercontent.com/33398104/116287050-ca628100-a744-11eb-8a46-9abcb5b7a873.png)

**Comment by jangxx** [comment]
Okay sounds good. I actually still used an old driver from 2019 up until yesterday, and to reproduce your bug I am in the process of upgrading now (haven't restarted my PC yet). As soon as that is done and I have verified that the library still works I will upload a new version to npm.

Edit: Version 1.2.1 is published to npm now.
